### ISSUE TITLE
Iter returns Desktop Entries in reverse order of importance

### ISSUE THREAD

**Issue by ryanabx** [pop-os/freedesktop-desktop-entry#8]
Let me know if I'm understanding this incorrectly:

This is the output of all the desktop files processed with Iter::new(default_paths())

    // Iter::new(default_paths())
    Local: /var/home/ryanbrue/.local/share/applications/discord-278329593012682754.desktop
    System: /usr/share/applications/geoclue-demo-agent.desktop
    System: /usr/share/applications/xdg-desktop-portal-gtk.desktop
    System: /usr/share/applications/rstudio.desktop
    System: /usr/share/applications/java-17-openjdk-17.0.9.0.9-3.fc39.x86_64-jconsole.desktop
    System: /usr/share/applications/org.gnome.Epiphany.desktop
    System: /usr/share/applications/gtk3-demo.desktop
    System: /usr/share/applications/gtk3-icon-browser.desktop
    System: /usr/share/applications/gtk3-widget-factory.desktop
    System: /usr/share/applications/com.system76.CosmicBackground.desktop
    System: /usr/share/applications/firefox.desktop
    System: /usr/share/applications/org.gnome.tweaks.desktop
    System: /usr/share/applications/code-url-handler.desktop
    System: /usr/share/applications/code.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Logs.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Evince-previewer.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Evince.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Contacts.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.font-viewer.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.fedoraproject.MediaWriter.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.clocks.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Extensions.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.baobab.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Connections.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Weather.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Characters.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Calculator.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.TextEditor.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Maps.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Loupe.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Calendar.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Boxes.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.github.tchx84.Flatseal.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gimp.GIMP.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.kde.krita.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.usebottles.bottles.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.gnome.Fractal.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.visualstudio.code-url-handler.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.visualstudio.code.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.spotify.Client.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/im.riot.Riot.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.base.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.calc.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.draw.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.impress.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.math.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.writer.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.libreoffice.LibreOffice.xsltfilter.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.inkscape.Inkscape.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.onlyoffice.desktopeditors.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.prismlauncher.PrismLauncher.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/io.github.shiftey.Desktop.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.valvesoftware.Steam.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.discordapp.Discord.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.mozilla.firefox.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/org.kde.neochat.desktop
    SystemFlatpak: /var/lib/flatpak/exports/share/applications/com.google.Chrome.desktop

And this is the output of default_paths():

    // default_paths()
    LocalFlatpak
    SystemFlatpak
    SystemLocal
    System
    Local

Seems like Iter reverses the order of importance. Also here is my $XDG_DATA_DIRS for confirmation:

    # $XDG_DATA_DIRS
    /var/home/ryanbrue/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
    

I believe this is the source of at least one bug: https://github.com/pop-os/cosmic-applets/issues/258

**Comment by ryanabx** [comment]
Also, here's the XDG Base Directory Specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by mmstick** [comment]
Published as 0.5.1
